[project]
name = "dash-calendar-timeline"
version = "2026.1.0-dev"
requires-python = ">=3.12"
dependencies = [
    "build>=1.3.0",
    "dash[dev]>=3.0.0",
    "wheel>=0.45.1",
]

[dependency-groups]
dev = [
    "ruff>=0.14.0",
]
